---
name: Create new Talos assets

on:
  schedule:
    - cron: '0 * * * *'
      
  workflow_dispatch:
    inputs:
      pushToRegistry:
        description: "Push image to ghcr registry?"
        default: true
        type: boolean
        required: false
      createRelease:
        description: "Create release in repository?"
        default: true
        type: boolean
        required: false
      forceBuild:
        description: "Force talos build"
        default: false
        type: boolean
        required: false

jobs:
  create-release:
    uses: mmalyska/github-workflows/.github/workflows/talos-create-release.yaml@main
    permissions:
      contents: write
      packages: write
    secrets:
      containerRegistryPassword: ${{ secrets.GITHUB_TOKEN }}
    with:
      pushToRegistry: ${{ inputs.pushToRegistry || true }}
      createRelease: ${{ inputs.createRelease || true }}
      repositoryName: ${{ github.repository }}
      containerRepositoryName: 'mmalyska/talos-installer'
      containerRegistryName: 'ghcr.io'
      containerRegistryUsername: ${{ github.actor }}
      archList: '[ "amd64", "arm64" ]'
      talosExtensionsImage: |
        --system-extension-image ghcr.io/siderolabs/i915-ucode:20240909 \
        --system-extension-image ghcr.io/siderolabs/intel-ucode:20240910
      forceBuild: ${{ inputs.forceBuild || false }}
